//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P15R01_MVC_CDQV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GenJunCCREntities : DbContext
    {
        public GenJunCCREntities()
            : base("name=GenJunCCREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camiones> Camiones { get; set; }
        public virtual DbSet<Choferes> Choferes { get; set; }
        public virtual DbSet<Rutas> Rutas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VWCamiones> VWCamiones { get; set; }
        public virtual DbSet<VWChoferes> VWChoferes { get; set; }
        public virtual DbSet<VWRutas> VWRutas { get; set; }
    
        public virtual ObjectResult<string> Insert_Camion(string matricula, string tipoCamion, Nullable<int> modelo, string marca, Nullable<int> capacidad, Nullable<double> kilometraje, Nullable<bool> disponibilidad, string urlFoto)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var tipoCamionParameter = tipoCamion != null ?
                new ObjectParameter("TipoCamion", tipoCamion) :
                new ObjectParameter("TipoCamion", typeof(string));
    
            var modeloParameter = modelo.HasValue ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(int));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var kilometrajeParameter = kilometraje.HasValue ?
                new ObjectParameter("Kilometraje", kilometraje) :
                new ObjectParameter("Kilometraje", typeof(double));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Insert_Camion", matriculaParameter, tipoCamionParameter, modeloParameter, marcaParameter, capacidadParameter, kilometrajeParameter, disponibilidadParameter, urlFotoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_Delete_Camion(Nullable<int> idCamion)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_Camion", idCamionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Delete_Chofer(Nullable<int> idChofer)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Delete_Chofer", idChoferParameter);
        }
    
        public virtual int sp_Delete_Ruta(Nullable<int> idRuta)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("IdRuta", idRuta) :
                new ObjectParameter("IdRuta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_Ruta", idRutaParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Existe_Licencia(string licencia)
        {
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Existe_Licencia", licenciaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Existe_Matricula(string matricula)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Existe_Matricula", matriculaParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<string> sp_Insert_Choferes(string nombre, string apPaterno, string apMaterno, string telefono, Nullable<System.DateTime> fechaNacimiento, string licencia, string urlFoto, Nullable<bool> disponibilidad, Nullable<System.DateTime> fechaRegistro)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("ApPaterno", apPaterno) :
                new ObjectParameter("ApPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("ApMaterno", apMaterno) :
                new ObjectParameter("ApMaterno", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("FechaRegistro", fechaRegistro) :
                new ObjectParameter("FechaRegistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Insert_Choferes", nombreParameter, apPaternoParameter, apMaternoParameter, telefonoParameter, fechaNacimientoParameter, licenciaParameter, urlFotoParameter, disponibilidadParameter, fechaRegistroParameter);
        }
    
        public virtual int sp_Insert_Rutas(Nullable<int> idChofer, Nullable<int> idCamion, string origen, string destino, Nullable<System.DateTime> fechaSalida, Nullable<System.DateTime> fechaLlegada, Nullable<bool> aTiempo, Nullable<double> distancia)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var fechaLlegadaParameter = fechaLlegada.HasValue ?
                new ObjectParameter("FechaLlegada", fechaLlegada) :
                new ObjectParameter("FechaLlegada", typeof(System.DateTime));
    
            var aTiempoParameter = aTiempo.HasValue ?
                new ObjectParameter("ATiempo", aTiempo) :
                new ObjectParameter("ATiempo", typeof(bool));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("Distancia", distancia) :
                new ObjectParameter("Distancia", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_Rutas", idChoferParameter, idCamionParameter, origenParameter, destinoParameter, fechaSalidaParameter, fechaLlegadaParameter, aTiempoParameter, distanciaParameter);
        }
    
        public virtual ObjectResult<sp_Listar_Camiones_Result> sp_Listar_Camiones(Nullable<bool> disponibilidad)
        {
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Listar_Camiones_Result>("sp_Listar_Camiones", disponibilidadParameter);
        }
    
        public virtual ObjectResult<sp_Obtener_Camion_ID_Result> sp_Obtener_Camion_ID(Nullable<int> idCamion)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Obtener_Camion_ID_Result>("sp_Obtener_Camion_ID", idCamionParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_Select_Camion_Result> sp_Select_Camion(string matricula)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Select_Camion_Result>("sp_Select_Camion", matriculaParameter);
        }
    
        public virtual ObjectResult<sp_Select_Chofer_Result> sp_Select_Chofer(Nullable<bool> disponibilidad)
        {
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Select_Chofer_Result>("sp_Select_Chofer", disponibilidadParameter);
        }
    
        public virtual ObjectResult<sp_Select_Rutas_Result> sp_Select_Rutas(Nullable<int> idRuta)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("IdRuta", idRuta) :
                new ObjectParameter("IdRuta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Select_Rutas_Result>("sp_Select_Rutas", idRutaParameter);
        }
    
        public virtual ObjectResult<sp_Select_Rutas_Detalle_Result> sp_Select_Rutas_Detalle()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Select_Rutas_Detalle_Result>("sp_Select_Rutas_Detalle");
        }
    
        public virtual int sp_Update_Camion(Nullable<int> idCamion, string matricula, string tipoCamion, Nullable<int> modelo, string marca, Nullable<int> capacidad, Nullable<double> kilometraje, Nullable<bool> disponibilidad, string urlFoto)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var tipoCamionParameter = tipoCamion != null ?
                new ObjectParameter("TipoCamion", tipoCamion) :
                new ObjectParameter("TipoCamion", typeof(string));
    
            var modeloParameter = modelo.HasValue ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(int));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var kilometrajeParameter = kilometraje.HasValue ?
                new ObjectParameter("Kilometraje", kilometraje) :
                new ObjectParameter("Kilometraje", typeof(double));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_Camion", idCamionParameter, matriculaParameter, tipoCamionParameter, modeloParameter, marcaParameter, capacidadParameter, kilometrajeParameter, disponibilidadParameter, urlFotoParameter);
        }
    
        public virtual ObjectResult<string> sp_Update_Choferes(Nullable<int> idChofer, string nombre, string apPaterno, string apMaterno, string telefono, Nullable<System.DateTime> fechaNacimiento, string licencia, string urlFoto, Nullable<bool> disponibilidad)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("ApPaterno", apPaterno) :
                new ObjectParameter("ApPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("ApMaterno", apMaterno) :
                new ObjectParameter("ApMaterno", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Update_Choferes", idChoferParameter, nombreParameter, apPaternoParameter, apMaternoParameter, telefonoParameter, fechaNacimientoParameter, licenciaParameter, urlFotoParameter, disponibilidadParameter);
        }
    
        public virtual ObjectResult<string> sp_Update_Rutas(Nullable<int> idRuta, Nullable<int> idChofer, Nullable<int> idCamion, string origen, string destino, Nullable<System.DateTime> fechaSalida, Nullable<System.DateTime> fechaLlegada, Nullable<bool> aTiempo, Nullable<double> distancia)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("IdRuta", idRuta) :
                new ObjectParameter("IdRuta", typeof(int));
    
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var fechaLlegadaParameter = fechaLlegada.HasValue ?
                new ObjectParameter("FechaLlegada", fechaLlegada) :
                new ObjectParameter("FechaLlegada", typeof(System.DateTime));
    
            var aTiempoParameter = aTiempo.HasValue ?
                new ObjectParameter("ATiempo", aTiempo) :
                new ObjectParameter("ATiempo", typeof(bool));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("Distancia", distancia) :
                new ObjectParameter("Distancia", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Update_Rutas", idRutaParameter, idChoferParameter, idCamionParameter, origenParameter, destinoParameter, fechaSalidaParameter, fechaLlegadaParameter, aTiempoParameter, distanciaParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
